### ISSUE TITLE
Relax numpy requirements to >= 1.13.3

### ISSUE THREAD

**Issue by mlubin** [conda-forge/or-tools-feedstock#8]
This package seems to have a requirement of numpy >= 1.18.5, which is causes trouble when integrating ortools with cvxpy, see https://github.com/cvxpy/cvxpy/pull/1655#issuecomment-1039238706. Setting >= 1.13.3 would match the version bounds in the official package: https://github.com/google/or-tools/blob/stable/ortools/python/setup.py.in#L47. Is there extra context for why >= 1.13.3 isn't allowed?

Relevant configuration(?):

https://github.com/conda-forge/or-tools-feedstock/blob/c331915da5c25ecabb4d73633d503f7427c5cf1e/recipe/meta.yaml#L111-L117

CC @Mizux @lperron

**Comment by BastianZim** [comment]
This restriction comes from the global conda-forge package pinning: https://conda-forge.org/docs/maintainer/pinning_deps.html

This is added to ensure that all conda-forge packages can be installed in the same environment without any islands of compatible packages occurring. 

See also this for info about the possible NumPy versions: https://conda-forge.org/docs/maintainer/knowledge_base.html#building-against-numpy

Can you elaborate a bit more on what exactly you are trying to achieve with this? Conda-forge also packages cvxpy  (https://github.com/conda-forge/cvxpy-feedstock) where a compatible NumPy is inserted so at least on the conda-forge side no problem should occur.

**Comment by mlubin** [comment]
I see, thanks for filling in the details. The issue is that cvxpy explicitly pins NumPy to 1.16 in their CI config (https://github.com/cvxpy/cvxpy/blob/master/continuous_integration/install_dependencies.sh), and `ortools-python` fails to install in that configuration. Now I'm wondering why the other packages that cvxpy installs which similarly have `{{ pin_compatible('numpy') }} ` (like osqp) don't cause the same problem.

**Comment by BastianZim** [comment]
I haven't checked this in-depth but you are using multiple channels in your setup (defaults and conda-forge, from what I can see) which is where this mismatch probably comes from, as some of the defaults packages are compiled in a different environment.

Unfortunately conda-forge does not guarantee compatibility with other channels so you'd have to restrict yourself to one of them if you want to be absolutely sure that everything works.

On a side note: I would recommend switching `conda` to the faster [`mamba`](https://github.com/mamba-org/mamba) solver as that not only saves you CI time, it also gives you much better solver error messages.

**Comment by mlubin** [comment]
Thanks, I'll close this since the issue doesn't seem to be here.
